# Generated by Django 4.2.7 on 2023-11-29 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deployment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("booking", "Booking"),
                            ("hotel", "Hotel"),
                            ("packages", "Packages"),
                            ("ticket", "Ticket"),
                            ("user", "User"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "lb_strategy",
                    models.CharField(
                        choices=[
                            ("round_robin", "Round Robin"),
                            ("least_conns", "Least Connections"),
                            ("power_of_2", "Power of 2"),
                            ("random", "Random"),
                            ("ip_hash", "IP Hash"),
                            ("weighted_round_robin", "Weighted Round Robin"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "scaler_strategy",
                    models.CharField(
                        choices=[("threshold", "Threshold-based"), ("time_series", "Time Series-based")],
                        max_length=100,
                    ),
                ),
                ("scaler_cpu_threshold", models.DecimalField(decimal_places=2, max_digits=5)),
                ("scaler_mem_threshold", models.DecimalField(decimal_places=2, max_digits=5)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
